name: Hugo Publish

on:
  push:
    branches:
    - master

jobs:
jobs:
  hugo-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build Hugo site
        run: hugo --minify --gc -t hugo-book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_REPO_TOKEN }}
          publish_dir: ./resources
  # update-main:
  #      - name: Deploy and publish updates
  #        run: |
  #          git config --global user.email "action@github.com"
  #          git config --global user.name "GitHub Action"
  #          git checkout -b gh-pages
  #          git add -f . # Force add all changes
  #          git commit -m "[chore] Auto publish"
  #         #  git push -u origin gh-pages -f
